#!/usr/bin/env bash
#
# Test zone management operations for qcow2 file.
#

#seq="$(basename $0)"
echo "QA output created by $seq"
#status=1 # failure is the default!

#_cleanup()
#{
#  _cleanup_test_img
#}
#trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
#. ../common.rc
#. ../common.filter
#. ../common.qemu

# This test only runs on Linux hosts with qcow2 image files.
#_supported_fmt qcow2
#_supported_proto file
#_supported_os Linux

IMG="--image-opts -n driver=qcow2,file.driver=file,file.filename=test.qcow2"
QEMU_IO="build/qemu-io"
#QEMU_IO_OPTIONS=$QEMU_IO_OPTIONS_NO_FMT
./build/qemu-img create -f qcow2 test.qcow2 -o size=768M -o zone_size=67108864 -o zone_nr_conv=0 -o zone_nr_seq=12 -o max_append_sectors=4 -o max_open_zones=4 -o max_active_zones=8 -o zm=zbd

#echo "case 1: if the operations work"
#echo "(1) report the first zone:"
#$QEMU_IO $IMG -c "zrp 0 1"
#echo
#echo "report the first 10 zones"
#$QEMU_IO $IMG -c "zrp 0 10"
#echo
#echo "report the last zone:"
#$QEMU_IO $IMG -c "zrp 0x2c000000 2" # 0x20000000 / 512 = 0x160000
#echo
#echo
#echo "(2) opening the first zone"
#$QEMU_IO $IMG -c "zo 0 67108864"  # 67108864 / 512 = 131072
#echo "report after:"
#$QEMU_IO $IMG -c "zrp 0 1"
#echo
#echo "opening the second zone"
#$QEMU_IO $IMG -c "zo 0x4000000 67108864"
#echo "report after:"
#$QEMU_IO $IMG -c "zrp 0x4000000 1"
#echo
#echo "opening the last zone"
#$QEMU_IO $IMG -c "zo 0x2c000000 67108864"
#echo "report after:"
#$QEMU_IO $IMG -c "zrp 0x2c000000 1" # 0x20000000 / 512 = 0x160000
#echo
#echo
zone_size=67108864
nr_zone=12

for ((i=0; i<$nr_zone; i++))
do
  echo "opening zone[$i]"
  offset=$((i * zone_size))
  $QEMU_IO $IMG -c "zo $offset $zone_size"  # 67108864 / 512 = 131072
  echo "report after:"
  $QEMU_IO $IMG -c "zrp $offset 1"
done

#echo "(3) closing the first zone"
#$QEMU_IO $IMG -c "zc 0 67108864"  # 67108864 / 512 = 131072
#echo "report after:"
#$QEMU_IO $IMG -c "zrp 0 1"
#echo
#echo "closing the last zone"
#$QEMU_IO $IMG -c "zc 0x2c000000 0x2000000"
#echo "report after:"
#$QEMU_IO $IMG -c "zrp 0x2c000000 1" # 0x2c000000 / 512 = 0x160000
#echo
#echo
#echo "(4) finishing the second zone"
#$QEMU_IO $IMG -c "zf 0x4000000 0x2000000"
#echo "report after:"
#$QEMU_IO $IMG -c "zrp 0x4000000 1"
echo
echo
echo "(5) resetting the second zone"
$QEMU_IO $IMG -c "zrs 0x4000000 67108864"
echo "report after:"
$QEMU_IO $IMG -c "zrp 0x4000000 1"
echo "resetting all"
$QEMU_IO $IMG -c "zrs 0 805306368"
echo "report after:"
$QEMU_IO $IMG -c "zrp 0 12"
#echo
#echo
echo "append write" # the physical block size of the device is 4096
for ((i=0; i<$nr_zone; i++))
do
  echo "zap zone[$i]"
  $QEMU_IO $IMG -c "zap -p 0 0x1000 0x2000"  # 67108864 / 512 = 131072
  echo "report after:"
  $QEMU_IO $IMG -c "zrp 0 1"
done

# success, all done
echo "*** done"
#rm -f $seq.full
status=0
